/**
 * testgen.ts — Auto regression test generator for logbook.
 *
 * For each patched symbol, generates a minimal test skeleton
 * that exercises the changed function's interface.
 *
 * Supports: Jest (TS/JS), pytest (Python), go test (Go).
 */

import * as path from "path";
import type { PatchPlan, PatchTarget } from "../memory/types.js";
import { detectLanguage } from "./parser.js";

// ─── Test Templates ─────────────────────────────────────────────────────────

interface TestTemplate {
    generate(target: PatchTarget, filePath: string): string;
    fileExtension: string;
    testFilePattern: (basename: string) => string;
}

const jestTemplate: TestTemplate = {
    fileExtension: ".test.ts",
    testFilePattern: (basename) => `${basename}.test.ts`,
    generate(target: PatchTarget, filePath: string): string {
        const relPath = path.basename(filePath).replace(/\.(ts|js|tsx|jsx)$/, "");
        const importPath = `./${relPath}`;

        if (target.nodeType === "class") {
            return `import { ${target.nodeName} } from '${importPath}';

describe('${target.nodeName}', () => {
  it('should be defined', () => {
    expect(${target.nodeName}).toBeDefined();
  });

  it('should instantiate correctly', () => {
    // TODO: Add constructor arguments as needed
    const instance = new ${target.nodeName}();
    expect(instance).toBeInstanceOf(${target.nodeName});
  });

  // TODO: Add tests for methods modified in this patch
  // Changed lines: ${target.startLine + 1}-${target.endLine + 1}
});
`;
        }

        if (target.nodeType === "function" || target.nodeType === "method") {
            return `import { ${target.nodeName} } from '${importPath}';

describe('${target.nodeName}', () => {
  it('should be defined', () => {
    expect(${target.nodeName}).toBeDefined();
  });

  it('should return expected result', () => {
    // TODO: Add appropriate arguments and expected values
    const result = ${target.nodeName}();
    expect(result).toBeDefined();
  });

  it('should handle edge cases', () => {
    // TODO: Test boundary conditions for the change
    // Changed lines: ${target.startLine + 1}-${target.endLine + 1}
  });
});
`;
        }

        return `// TODO: Add regression test for ${target.nodeType} "${target.nodeName}"
// Changed lines: ${target.startLine + 1}-${target.endLine + 1}
`;
    },
};

const pytestTemplate: TestTemplate = {
    fileExtension: ".py",
    testFilePattern: (basename) => `test_${basename}.py`,
    generate(target: PatchTarget, filePath: string): string {
        const moduleName = path.basename(filePath).replace(/\.py$/, "");

        if (target.nodeType === "class") {
            return `"""Regression tests for ${target.nodeName} (auto-generated by logbook)."""

from ${moduleName} import ${target.nodeName}


class Test${target.nodeName}:
    """Tests for ${target.nodeName}."""

    def test_instantiation(self):
        """Ensure ${target.nodeName} can be instantiated."""
        # TODO: Add constructor arguments as needed
        instance = ${target.nodeName}()
        assert instance is not None

    def test_regression(self):
        """Regression test for changes at lines ${target.startLine + 1}-${target.endLine + 1}."""
        # TODO: Add specific assertions for the patched behavior
        pass
`;
        }

        return `"""Regression tests for ${target.nodeName} (auto-generated by logbook)."""

from ${moduleName} import ${target.nodeName}


def test_${target.nodeName}_exists():
    """Ensure ${target.nodeName} is importable."""
    assert ${target.nodeName} is not None


def test_${target.nodeName}_basic():
    """Basic test for ${target.nodeName}."""
    # TODO: Add appropriate arguments and expected values
    result = ${target.nodeName}()
    assert result is not None


def test_${target.nodeName}_regression():
    """Regression test for changes at lines ${target.startLine + 1}-${target.endLine + 1}."""
    # TODO: Add specific assertions for the patched behavior
    pass
`;
    },
};

const goTestTemplate: TestTemplate = {
    fileExtension: ".go",
    testFilePattern: (basename) => `${basename}_test.go`,
    generate(target: PatchTarget, filePath: string): string {
        const packageName = path.basename(path.dirname(filePath));

        if (target.nodeType === "function" || target.nodeType === "method") {
            const titleCase =
                target.nodeName.charAt(0).toUpperCase() + target.nodeName.slice(1);

            return `package ${packageName}

import "testing"

func Test${titleCase}(t *testing.T) {
	t.Run("basic", func(t *testing.T) {
		// TODO: Add appropriate arguments and expected values
		// Changed lines: ${target.startLine + 1}-${target.endLine + 1}
	})

	t.Run("regression", func(t *testing.T) {
		// TODO: Verify patched behavior
	})
}
`;
        }

        return `package ${packageName}

import "testing"

// TODO: Add regression test for ${target.nodeType} "${target.nodeName}"
// Changed lines: ${target.startLine + 1}-${target.endLine + 1}
`;
    },
};

const rustTestTemplate: TestTemplate = {
    fileExtension: ".rs",
    testFilePattern: (basename) => `${basename}_test.rs`,
    generate(target: PatchTarget, filePath: string): string {
        return `#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_${target.nodeName.toLowerCase()}_exists() {
        // Regression test for ${target.nodeType} "${target.nodeName}"
        // Changed lines: ${target.startLine + 1}-${target.endLine + 1}
        // TODO: Add appropriate assertions
    }

    #[test]
    fn test_${target.nodeName.toLowerCase()}_regression() {
        // TODO: Verify patched behavior
    }
}
`;
    },
};

// ─── Template Registry ──────────────────────────────────────────────────────

const TEMPLATES: Record<string, TestTemplate> = {
    typescript: jestTemplate,
    javascript: jestTemplate,
    python: pytestTemplate,
    go: goTestTemplate,
    rust: rustTestTemplate,
};

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Generate regression test skeletons for all targets in a patch plan.
 * Returns an array of { filePath, content } pairs.
 */
export function generateTests(
    plan: PatchPlan
): { filePath: string; content: string }[] {
    const language = detectLanguage(plan.filePath);
    if (!language) return [];

    const template = TEMPLATES[language];
    if (!template) return [];

    const basename = path
        .basename(plan.filePath)
        .replace(/\.[^.]+$/, "");
    const testDir = path.dirname(plan.filePath);
    const testFileName = template.testFilePattern(basename);
    const testFilePath = path.join(testDir, testFileName);

    // Filter to only named targets (skip raw line targets)
    const namedTargets = plan.targets.filter(
        (t) => t.nodeType !== "raw" && t.nodeName !== ""
    );

    if (namedTargets.length === 0) return [];

    // Generate combined test file
    const parts: string[] = [];
    parts.push(
        `// Auto-generated regression tests by logbook patch engine\n`
    );
    parts.push(
        `// Patch: ${plan.description}\n`
    );
    parts.push(`// File: ${plan.filePath}\n\n`);

    for (const target of namedTargets) {
        parts.push(template.generate(target, plan.filePath));
        parts.push("\n");
    }

    return [
        {
            filePath: testFilePath,
            content: parts.join(""),
        },
    ];
}

/**
 * Get the test command for a given language.
 */
export function getTestCommand(language: string): string | null {
    switch (language) {
        case "typescript":
        case "javascript":
            return "npx jest --passWithNoTests";
        case "python":
            return "python -m pytest -x";
        case "go":
            return "go test ./...";
        case "rust":
            return "cargo test";
        default:
            return null;
    }
}
